"""
Simulated TEE enclave with sealing, attestation, and isolated memory (Appendix A §3-4).

A Trusted Execution Environment provides hardware-guaranteed isolation
for the governance process:

- **Sealing**: Cryptographically binding data to the enclave's measurement
- **Attestation**: Proving the enclave is running the expected code
- **Isolated memory**: The host OS cannot read enclave memory

This module is an **executable specification** of that interface, not a
security boundary (#311). What the simulation actually provides: sealing is a
plaintext in-process dict (nothing is encrypted or bound to anything); the
measurement is a SHA-256 of this module's own source bytes, or a
caller-supplied code hash - two instances built from the same code agree, and
an edited module changes it; attestation is unsigned, ``is_debug`` is always
False, and ``valid`` is never set False, so attestation cannot fail here.
Nothing in the governance path constructs :class:`SimulatedEnclave` - it
exists so Appendix A's interface has a testable shape. A production
deployment would use Intel SGX, AMD SEV-SNP, or ARM TrustZone.

Real-world analogy:
    The secure element in a payment terminal. When you enter your PIN,
    the terminal's secure chip processes it *inside* the chip. The rest
    of the terminal cannot read the PIN, even though they share the same
    physical device.
"""

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..identity.keys import GenesisManifest

#: The simulation's code measurement: a SHA-256 of this module's own source
#: bytes, computed once at import. The closest a pure-Python simulation gets
#: to a real enclave's measurement of its loaded code (#311).
_MODULE_MEASUREMENT = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()


@dataclass
class AttestationReport:
    """Report generated by the enclave's attestation mechanism.

    Attributes:
        enclave_hash: The enclave's code measurement - in this simulation the
            SHA-256 of the enclave module's source bytes (or the code hash
            the caller supplied at construction), not a hardware-derived
            quote of loaded pages.
        is_debug: Whether the enclave is running in debug mode. Always False
            in this simulation.
        sealed_data_hash: Hash of all sealed data stored inside the enclave.
        valid: Whether the attestation verification passed. Defaults True and
            nothing in the simulation ever sets it False: the report is
            unsigned and attestation cannot fail here (#311).
    """

    enclave_hash: str
    is_debug: bool
    sealed_data_hash: str
    valid: bool = True


class SimulatedEnclave:
    """Simulated TEE enclave for testing Nomos governance layer security properties.

    All operations are in-memory Python; the interface mirrors what a real
    SGX/SEV enclave would provide, and the module docstring states exactly
    which guarantees the simulation does not carry (#311).

    Args:
        genesis: Optional :class:`~..identity.keys.GenesisManifest` to
            initialise the enclave with the genesis root of trust.
        code_hash: Optional measurement to stand for the loaded code. When
            omitted, the measurement is the SHA-256 of this module's own
            source bytes, so two instances of the same code agree and an
            edited module measures differently.
    """

    def __init__(self, genesis: GenesisManifest | None = None, code_hash: str | None = None):
        self._genesis = genesis
        self._sealed_storage: dict[str, Any] = {}
        self._measurement = code_hash if code_hash is not None else _MODULE_MEASUREMENT
        self._attested = False

    def attest(self) -> AttestationReport:
        """Generate an attestation report for the current enclave state.

        The report includes the enclave's measurement and a hash of all
        sealed data. It is not signed, and its ``valid`` flag is never set
        False - in this simulation attestation cannot fail, so the report
        asserts identity without proving it to anyone (#311).

        Returns:
            An :class:`AttestationReport` with the current measurement.
        """
        self._attested = True
        sealed_hash = hashlib.sha256(str(self._sealed_storage).encode()).hexdigest()
        return AttestationReport(
            enclave_hash=self._measurement,
            is_debug=False,
            sealed_data_hash=sealed_hash,
        )

    def seal(self, key: str, value: Any):
        """Store data inside the enclave's sealed storage.

        In this simulation "sealed" means stored in a plaintext in-process
        dict: nothing is encrypted, keyed, or bound to the measurement, and
        the only isolation is the leading underscore on the attribute. A
        real enclave seals ciphertext bound to its measurement so no other
        code can unseal it; this records the interface's intent, not its
        protection (#311).

        Args:
            key: Identifier for the data.
            value: Any object; it is stored by reference, not serialised.
        """
        self._sealed_storage[key] = value

    def unseal(self, key: str) -> Any | None:
        """Retrieve data from sealed storage.

        Args:
            key: Identifier for the data.

        Returns:
            The stored value, or None if not found.
        """
        return self._sealed_storage.get(key)

    def verify_measurement(self, expected_hash: str) -> bool:
        """Verify that the enclave's measurement matches an expected hash.

        Used by the genesis bootstrapping protocol to confirm identity
        continuity after cold boot. Since #311 the measurement derives from
        the module source (or the caller's code hash), so two enclaves built
        from the same code agree, an edited module fails the check, and a
        cold boot of unchanged code preserves continuity - which is what
        this method existed to confirm and, with a per-instance random
        measurement, never could.

        Args:
            expected_hash: The hash to compare against.

        Returns:
            True if the enclave's measurement matches.
        """
        return self._measurement == expected_hash

    @property
    def is_attested(self) -> bool:
        """Whether the enclave has generated at least one attestation report."""
        return self._attested

    def cold_boot(self, genesis: GenesisManifest):
        """Reset the enclave to a fresh state with a new genesis manifest.

        This clears all sealed storage and attestation state, simulating a
        full hardware reset (see Appendix A §9.5). The measurement is
        preserved: a reboot re-measures the same loaded code, so identity
        continuity across cold boot is checkable via
        :meth:`verify_measurement` (#311).

        Args:
            genesis: The new genesis manifest for the rebooted enclave.
        """
        self._genesis = genesis
        self._sealed_storage = {}
        self._attested = False
