"""
Simulated TEE enclave with sealing, attestation, and isolated memory (Appendix A §3-4).

A Trusted Execution Environment provides hardware-guaranteed isolation
for the governance process:

- **Sealing**: Cryptographically binding data to the enclave's measurement
- **Attestation**: Proving the enclave is running the expected code
- **Isolated memory**: The host OS cannot read enclave memory

This module simulates these guarantees in software for testing. A production
deployment would use Intel SGX, AMD SEV-SNP, or ARM TrustZone.

Real-world analogy:
    The secure element in a payment terminal. When you enter your PIN,
    the terminal's secure chip processes it *inside* the chip. The rest
    of the terminal cannot read the PIN, even though they share the same
    physical device.
"""

import hashlib
import secrets
from dataclasses import dataclass
from typing import Any

from ..identity.keys import GenesisManifest


@dataclass
class AttestationReport:
    """Report generated by the enclave's attestation mechanism.

    Attributes:
        enclave_hash: The enclave's measurement (SHA-256 of its initial state).
        is_debug: Whether the enclave is running in debug mode
            (debug enclaves are not truly secure).
        sealed_data_hash: Hash of all sealed data stored inside the enclave.
        valid: Whether the attestation verification passed.
    """

    enclave_hash: str
    is_debug: bool
    sealed_data_hash: str
    valid: bool = True


class SimulatedEnclave:
    """Simulated TEE enclave for testing Nomos governance layer security properties.

    In simulation mode, all operations are in-memory Python. The interface
    mirrors what a real SGX/SEV enclave would provide.

    Args:
        genesis: Optional :class:`~..identity.keys.GenesisManifest` to
            initialise the enclave with the genesis root of trust.
    """

    def __init__(self, genesis: GenesisManifest | None = None):
        self._genesis = genesis
        self._sealed_storage: dict[str, Any] = {}
        self._measurement = hashlib.sha256(secrets.token_bytes(32)).hexdigest()
        self._attested = False

    def attest(self) -> AttestationReport:
        """Generate an attestation report for the current enclave state.

        The report includes the enclave's measurement and a hash of all
        sealed data. A remote verifier can use this to confirm the enclave
        is running the expected code with the expected data.

        Returns:
            An :class:`AttestationReport` with the current measurement.
        """
        self._attested = True
        sealed_hash = hashlib.sha256(str(self._sealed_storage).encode()).hexdigest()
        return AttestationReport(
            enclave_hash=self._measurement,
            is_debug=False,
            sealed_data_hash=sealed_hash,
        )

    def seal(self, key: str, value: Any):
        """Store data inside the enclave's sealed storage.

        Sealed data is cryptographically bound to the enclave's measurement.
        Only the same enclave instance can unseal it.

        Args:
            key: Identifier for the data.
            value: Any pickle-serialisable object.
        """
        self._sealed_storage[key] = value

    def unseal(self, key: str) -> Any | None:
        """Retrieve data from sealed storage.

        Args:
            key: Identifier for the data.

        Returns:
            The stored value, or None if not found.
        """
        return self._sealed_storage.get(key)

    def verify_measurement(self, expected_hash: str) -> bool:
        """Verify that the enclave's measurement matches an expected hash.

        Used by the genesis bootstrapping protocol to confirm identity
        continuity after cold boot.

        Args:
            expected_hash: The hash to compare against.

        Returns:
            True if the enclave's measurement matches.
        """
        return self._measurement == expected_hash

    @property
    def is_attested(self) -> bool:
        """Whether the enclave has generated at least one attestation report."""
        return self._attested

    def cold_boot(self, genesis: GenesisManifest):
        """Reset the enclave to a fresh state with a new genesis manifest.

        This clears all sealed storage and generates a new measurement,
        simulating a full hardware reset (see Appendix A §9.5).

        Args:
            genesis: The new genesis manifest for the rebooted enclave.
        """
        self._genesis = genesis
        self._sealed_storage = {}
        self._measurement = hashlib.sha256(secrets.token_bytes(32)).hexdigest()
        self._attested = False
