"""
Dashboard Tab 4: RL Training Results.

Loads CSV files from ``results/rl/`` generated by the training scripts.

Displays:
- Governed vs ungoverned comparison (reward, violations, vetoes)
- Training curves from per-rollout metrics
- Minigrid results (per-environment)
- SafetyGrid results (per-seed)
- Neo4j logging of RL run aggregates

Real-world analogy:
    A test track comparison between two cars. The governed car (with
    Neural Parliament) is compared against the ungoverned car (raw PPO)
    on metrics like lap time (reward), crashes (violations), and
    pit-stop overrides (vetoes).
"""

import contextlib
import os
from glob import glob

import altair as alt
import pandas as pd
import streamlit as st

from governance.benchmarks.analysis import _bootstrap_ci
from ..ontology.backend import OntologyBackend
RL_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))), "results", "rl"
)


def _csv_path(*parts: str) -> str:
    return os.path.join(RL_DIR, *parts)


def _load_csv(*parts: str) -> pd.DataFrame | None:
    path = _csv_path(*parts)
    if not os.path.exists(path):
        return None
    return pd.read_csv(path)


def _load_metrics(label: str) -> pd.DataFrame | None:
    return _load_csv(f"{label}_metrics.csv")


def _load_seed_metrics(label: str) -> list[pd.DataFrame]:
    """
    Load all per-seed training CSVs for a condition.

    Example:
        governed_seed0.csv
        governed_seed1.csv
        ...
    """
    pattern = _csv_path(f"{label}_seed*.csv")
    seed_files = sorted(glob(pattern))

    return [pd.read_csv(file) for file in seed_files]


def _compute_ci_dataframe(seed_dfs: list[pd.DataFrame], condition: str):
    if len(seed_dfs) < 2 or any(df.empty for df in seed_dfs):
        return None

    rows = []

    num_steps = min(len(df) for df in seed_dfs)

    if num_steps == 0:
        return None

    for step in range(num_steps):
        rewards = [df.iloc[step]["total_reward"] for df in seed_dfs]

        lower, upper = _bootstrap_ci(rewards)

        rows.append(
            {
                "step": step,
                "condition": condition,
                "mean_reward": sum(rewards) / len(rewards),
                "ci_lower": lower,
                "ci_upper": upper,
            }
        )

    return pd.DataFrame(rows)


def _load_summary() -> pd.DataFrame | None:
    return _load_csv("comparison_summary.csv")


def _load_minigrid_summary() -> pd.DataFrame | None:
    return _load_csv("minigrid", "comparison_summary.csv")


def _load_safety_summary() -> pd.DataFrame | None:
    return _load_csv("safety_grid", "comparison_summary.csv")


def _log_rl_to_backend(backend: OntologyBackend | None, label: str, row: dict):
    if backend is None:
        return
    with contextlib.suppress(Exception):
        backend.add_entity(
            "rl_run",
            {
                "label": label,
                "seed": row.get("seed", -1),
                "mean_reward": float(row.get("mean_reward", 0)),
                "std_reward": float(row.get("std_reward", 0)),
                "eval_violations": int(row.get("eval_violations", 0)),
                "eval_vetoes": int(row.get("eval_vetoes", 0)),
            },
        )


def _render_top_level(
    backend: OntologyBackend | None,
    show_statistics: bool = False,
):
    summary = _load_summary()
    gov_metrics = _load_metrics("governed")
    gov_seed_metrics = _load_seed_metrics("governed")
    ung_metrics = _load_metrics("ungoverned")
    ung_seed_metrics = _load_seed_metrics("ungoverned")

    gov_ci = _compute_ci_dataframe(
        gov_seed_metrics,
        "Governed",
    )
    ung_ci = _compute_ci_dataframe(
        ung_seed_metrics,
        "Ungoverned",
    )

    if show_statistics:
        st.subheader("📈 Summary Statistics")

        if summary is None or summary.empty:
            st.info(
                "No summary statistics available. Run the RL experiments first."
            )
        else:
            c1, c2, c3 = st.columns(3)

            c1.metric(
                "Average Reward",
                f"{summary['mean_reward'].mean():.2f}",
            )

            c2.metric(
                "Average Violations",
                f"{summary['eval_violations'].mean():.2f}",
            )

            c3.metric(
                "Average Vetoes",
                f"{summary['eval_vetoes'].mean():.2f}",
            )

        st.divider()

    if summary is not None and not summary.empty:
        st.subheader("Governed vs Ungoverned — Summary")

        for _, row in summary.iterrows():
            _log_rl_to_backend(backend, row["label"], row)

        pivot = summary.pivot_table(
            index="label",
            aggfunc="mean",
            values=["mean_reward", "std_reward", "eval_violations", "eval_apples", "eval_vetoes"],
        ).round(2)
        st.dataframe(pivot, use_container_width=True)

        st.divider()
        st.subheader("Per-Seed Comparison")
        bar_data = summary.copy()
        bar_data["seed_label"] = bar_data["label"] + " seed " + bar_data["seed"].astype(str)
        bar_chart = (
            alt.Chart(bar_data)
            .mark_bar()
            .encode(
                x=alt.X("seed_label:N", title="Condition", sort=None),
                y=alt.Y("mean_reward:Q", title="Mean Reward"),
                color=alt.Color("label:N", title=""),
                tooltip=["label", "seed", "mean_reward", "std_reward"],
            )
            .properties(height=250)
        )
        st.altair_chart(bar_chart, use_container_width=True)

    if gov_metrics is not None and ung_metrics is not None:
        st.divider()
        st.subheader("Training Curves")

        gov_metrics["condition"] = "Governed"
        ung_metrics["condition"] = "Ungoverned"
        combined = pd.concat([gov_metrics, ung_metrics], ignore_index=True)

        min_len = min(len(gov_metrics), len(ung_metrics))
        combined_trimmed = combined.groupby("condition").head(min_len).reset_index(drop=True)

        reward_chart = (
            alt.Chart(combined_trimmed)
            .mark_line(opacity=0.8)
            .encode(
                x=alt.X("step:Q", title="Training Step"),
                y=alt.Y("reward:Q", title="Reward"),
                color=alt.Color("condition:N", title="Training"),
                tooltip=[
                    alt.Tooltip("step:Q", title="Step"),
                    alt.Tooltip("reward:Q", title="Reward", format=".2f"),
                    alt.Tooltip("condition:N", title="Condition"),
                ],
            )
            .properties(height=200)
        )

        ci_frames = [
            df for df in [gov_ci, ung_ci] if df is not None and not df.empty
        ]
        if show_statistics and ci_frames:
            ci_combined = pd.concat(ci_frames, ignore_index=True)
            band = (
                alt.Chart(ci_combined)
                .mark_area(opacity=0.2)
                .encode(
                    x="step:Q",
                    y="ci_lower:Q",
                    y2="ci_upper:Q",
                    color=alt.Color("condition:N", title="Condition"),
                    tooltip=[
                        alt.Tooltip("step:Q", title="Step"),
                        alt.Tooltip("ci_lower:Q", title="CI Lower", format=".2f"),
                        alt.Tooltip("ci_upper:Q", title="CI Upper", format=".2f"),
                        alt.Tooltip("condition:N", title="Condition"),
                    ],
                )
            )
            reward_chart = band + reward_chart
        elif show_statistics and (
            len(gov_seed_metrics) < 2 or len(ung_seed_metrics) < 2
        ):
            st.info(
                "Confidence interval bands require multiple per-seed training runs."
            )

        st.altair_chart(reward_chart, use_container_width=True)

        if "violations" in combined_trimmed.columns:
            viol_chart = (
                alt.Chart(combined_trimmed)
                .mark_line(opacity=0.8)
                .encode(
                    x=alt.X("step:Q", title="Training Step"),
                    y=alt.Y("violations:Q", title="Constraint Violations"),
                    color=alt.Color("condition:N", title=""),
                    tooltip=[
                        alt.Tooltip("step:Q", title="Step"),
                        alt.Tooltip("violations:Q", title="Violations"),
                        alt.Tooltip("condition:N", title="Condition"),
                    ],
                )
                .properties(height=200)
            )
            st.altair_chart(viol_chart, use_container_width=True)

        gov_only = gov_metrics.copy()
        if "veto_count" in gov_only.columns:
            veto_chart = (
                alt.Chart(gov_only)
                .mark_line(color="purple", opacity=0.8)
                .encode(
                    x=alt.X("step:Q", title="Training Step"),
                    y=alt.Y("veto_count:Q", title="Veto Count"),
                    tooltip=[
                        alt.Tooltip("step:Q", title="Step"),
                        alt.Tooltip("veto_count:Q", title="Veto Count"),
                    ],
                )
                .properties(height=200)
            )
            st.altair_chart(veto_chart, use_container_width=True)

    if summary is None and (gov_metrics is None or ung_metrics is None):
        st.info(
            "No RL results found in `results/rl/`. Run `python scripts/train_governed_agent.py` first."
        )


def _render_minigrid(backend: OntologyBackend | None):
    summary = _load_minigrid_summary()
    if summary is None or summary.empty:
        st.info("No Minigrid results found in `results/rl/minigrid/`.")
        return

    st.subheader("Minigrid Environments")

    for env_name in summary["env"].unique():
        env_data = summary[summary["env"] == env_name]
        with st.expander(env_name, expanded=True):
            st.dataframe(env_data, use_container_width=True, hide_index=True)

            bar_chart = (
                alt.Chart(env_data)
                .mark_bar()
                .encode(
                    x=alt.X("label:N", title="Condition"),
                    y=alt.Y("mean_reward:Q", title="Mean Reward"),
                    color=alt.Color("label:N", title=""),
                    column=alt.Column("seed:N", title="Seed"),
                )
                .properties(height=200)
            )
            st.altair_chart(bar_chart, use_container_width=True)

            if "eval_vetoes" in env_data.columns:
                veto_chart = (
                    alt.Chart(env_data)
                    .mark_bar(color="purple")
                    .encode(
                        x=alt.X("label:N", title="Condition"),
                        y=alt.Y("eval_vetoes:Q", title="Vetoes"),
                        column=alt.Column("seed:N", title="Seed"),
                    )
                    .properties(height=150)
                )
                st.altair_chart(veto_chart, use_container_width=True)

            for _, row in env_data.iterrows():
                _log_rl_to_backend(backend, f"minigrid_{env_name}", row)

            seed_csv = _load_csv("minigrid", f"governed_{env_name}_seed0.csv")
            if seed_csv is not None and not seed_csv.empty:
                st.caption("Training curve (governed, seed 0)")
                curve_chart = (
                    alt.Chart(seed_csv)
                    .mark_line(opacity=0.7)
                    .encode(
                        x=alt.X("step:Q", title="Episode"),
                        y=alt.Y("total_reward:Q", title="Reward"),
                    )
                    .properties(height=150)
                )
                st.altair_chart(curve_chart, use_container_width=True)


def _render_safety(backend: OntologyBackend | None):
    summary = _load_safety_summary()
    if summary is None or summary.empty:
        st.info("No SafetyGrid results found in `results/rl/safety_grid/`.")
        return

    st.subheader("Safety Grid World")

    st.dataframe(summary, use_container_width=True, hide_index=True)

    for _, row in summary.iterrows():
        _log_rl_to_backend(backend, "safety_grid", row)

    if "mean_reward" in summary.columns:
        bar_chart = (
            alt.Chart(summary)
            .mark_bar()
            .encode(
                x=alt.X("label:N", title="Condition"),
                y=alt.Y("mean_reward:Q", title="Mean Reward"),
                color=alt.Color("label:N", title=""),
                column=alt.Column("seed:N", title="Seed"),
            )
            .properties(height=200)
        )
        st.altair_chart(bar_chart, use_container_width=True)

    seed_csv = _load_csv("safety_grid", "governed_seed0.csv")
    if seed_csv is not None and not seed_csv.empty:
        st.caption("Training curve (governed, seed 0)")
        cost_col = "total_cost" if "total_cost" in seed_csv.columns else "total_reward"
        curve_chart = (
            alt.Chart(seed_csv)
            .mark_line(opacity=0.7)
            .encode(
                x=alt.X("step:Q", title="Step"),
                y=alt.Y(f"{cost_col}:Q", title=cost_col),
            )
            .properties(height=150)
        )
        st.altair_chart(curve_chart, use_container_width=True)


def render_rl_tab(
    backend: OntologyBackend | None = None,
    show_statistics: bool = False,
):
    st.header("🤖 RL Training Results")
    st.caption(
        "Comparison between governed (Neural Parliament) and ungoverned (raw PPO) agents."
    )

    if show_statistics:
        st.info(
            "Statistical annotations are enabled. Confidence intervals and effect-size "
            "information will be shown where available."
        )

    _render_top_level(
        backend,
        show_statistics=show_statistics,
    )
    st.divider()
    _render_minigrid(backend)

    st.divider()
    _render_safety(backend)
